// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK2Np3RuWghrM9xwc7futrpM_Bb0mjaUI',
    appId: '1:204353932034:android:b4d348cb12fde59303501b',
    messagingSenderId: '204353932034',
    projectId: 'ourpass-app',
    storageBucket: 'ourpass-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCU-G2-nOgHnYsxzrhrdVOD56dApqB7U',
    appId: '1:204353932034:ios:6263ba74cdd3f6bd03501b',
    messagingSenderId: '204353932034',
    projectId: 'ourpass-app',
    storageBucket: 'ourpass-app.appspot.com',
    iosClientId: '204353932034-rjs9tgram2de2ac29j4phufs16f998kn.apps.googleusercontent.com',
    iosBundleId: 'test.app.ourpass',
  );
}
